DentistBooking/DentistBookingWebApp/Pages/Account/Details/Admin.cshtml.cs
using DataAccess.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Security.Claims;

namespace DentistBookingWebApp.Pages.Account.Details
{
    [Authorize(Roles = "Admin")]
    public class AdminModel : PageModel
    {
        private readonly IAdminRepository adminRepository;
        public AdminModel(IAdminRepository adminRepository)
        {
            this.adminRepository = adminRepository;
        }

        public ViewModels.Admin Admin { get; set; }

        public IActionResult OnGet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            try
            {
                BusinessObject.Admin admin = adminRepository.GetAdminByUserId((int)id);

                if (admin == null)
                {
                    return NotFound();
                }
                Admin = new ViewModels.Admin
                {
                    Id = admin.Id,
                    FullName = admin.FullName,
                    PhoneNumber = admin.PhoneNumber,
                    UserId = admin.UserId,
                    User = new ViewModels.User
                    {
                        Id = admin.User.Id,
                        Password = admin.User.Password,
                        RoleId = admin.User.RoleId,
                        Email = admin.User.Email,
                        Role = admin.User.Role
                    }
                };

                return Page();
            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = "There is an error. Please try again";
                return RedirectToPage("/Index");
            }
        }
    }
}

DentistBooking/DentistBookingWebApp/Pages/Account/Details/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using BusinessObject;
using BusinessObject.Data;
using DataAccess.Interfaces;
using Microsoft.AspNetCore.Authorization;
using System.ComponentModel.DataAnnotations;
using DentistBookingWebApp.Validation;

namespace DentistBookingWebApp.Pages.Admin.CustomerPage
{
    [Authorize(Roles ="Admin")]
    public class CreateModel : PageModel
    {
        private readonly IUserRepository userRepository;
        private readonly ICustomerRepository customerRepository;
        public CreateModel(IUserRepository _userRepository, ICustomerRepository _customerRepository)
        {
            userRepository = _userRepository;
            customerRepository = _customerRepository;
        }

        [BindProperty]
        [Required]
        [Display(Name = "Email")]
        [EmailAddress(ErrorMessage = "Invalid email address")]
        public string Email { get; set; }

        [BindProperty]
        [Required]
        [Display(Name = "Password")]
        [DataType(DataType.Password)]
        [StringLength(50, ErrorMessage = "Password length must be between 6 and 50", MinimumLength = 6)]
        public string Password { get; set; }

        [BindProperty]
        public ViewModels.Customer Customer { get; set; }

       
        public void OnGet()
        {
        }
        public IActionResult OnPost()
        {
            try
            {
                if (SignUpValidation.CheckEmail(Email))
                {
                    ModelState.AddModelError("Email", "This email already exists");
                }
                if (SignUpValidation.CheckPhoneCustomer(Customer.PhoneNumber))
                {
                    ModelState.AddModelError("Customer.PhoneNumber", "This phone number already exists");
                }
                if (ModelState.IsValid)
                {
                    User userObj = new User
                    {
                        Email = Email,
                        Password = Validation.HashCode.HashPassword(Password),
                        RoleId = 2
                    };

                    int userId = userRepository.SignUp(userObj);
                    if (userId > 0)
                    {
                        BusinessObject.Customer customerObj = new BusinessObject.Customer
                        {
                            FullName = Customer.FullName,
                            PhoneNumber = Customer.PhoneNumber,
                            UserId = userId
                        };
                        customerRepository.AddNewCustomer(customerObj);
                        return RedirectToPage("/Admin/Account");
                    }
                    else
                    {
                        ViewData["Message"] = "Cannot add customer!";
                        return Page();
                    }
                }
                else
                {
                    return Page();
                }
            }
            catch (Exception ex)
            {
                ViewData["Message"] = ex.Message;
                return Page();
            }
        }
    }
}

DentistBooking/DentistBookingWebApp/Pages/Account/Details/Customer.cshtml.cs
using BusinessObject;
using DataAccess.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Security.Claims;

namespace DentistBookingWebApp.Pages.Account.Details
{
    [Authorize]
    public class CustomerModel : PageModel
    {
        private readonly ICustomerRepository customerRepository;
        public CustomerModel(ICustomerRepository customerRepository)
        {
            this.customerRepository = customerRepository;
        }

        public ViewModels.Customer Customer { get; set; }
        public IActionResult OnGet(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            int userId = int.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            string role = User.FindFirstValue(ClaimTypes.Role);


            if(role == "Customer" && userId != id)
            {
                return NotFound();
            }

            try
            {
                Customer customer = customerRepository.GetCustomerByUserId((int)id);

                if (customer == null)
                {
                    return NotFound();
                }
                Customer = new ViewModels.Customer
                {
                    Id = customer.Id,
                    FullName = customer.FullName,
                    PhoneNumber = customer.PhoneNumber,
                    UserId = customer.UserId,
                    User = new ViewModels.User
                    {
                        Id = customer.User.Id,
                        Password = customer.User.Password,
                        RoleId = customer.User.RoleId,
                        Email = customer.User.Email,
                        Role = customer.User.Role
                    }
                };
                
                return Page();
            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = "There is an error. Please try again";
                return RedirectToPage("/Index");
            }
        }
    }
}

DentistBooking/DentistBookingWebApp/Pages/Reservation/Details.cshtml.cs
using BusinessObject;
using DataAccess.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Security.Claims;
using System.Threading.Tasks;

namespace DentistBookingWebApp.Pages.Reservation
{
    [Authorize]
    public class DetailsModel : PageModel
    {
        private readonly IReservationRepository reservationRepository;
        private readonly IUserRepository userRepository;
        private readonly IDentistRepository dentistRepository;
        private readonly ICustomerRepository customerRepository;
        private readonly IFeedbackRepository feedbackRepository;

        public DetailsModel(IReservationRepository reservationRepository,
                            IUserRepository userRepository,
                            IDentistRepository dentistRepository,
                            ICustomerRepository customerRepository,
                            IFeedbackRepository feedbackRepository)
        {
            this.reservationRepository = reservationRepository;
            this.dentistRepository = dentistRepository;
            this.userRepository = userRepository;
            this.customerRepository = customerRepository;
            this.feedbackRepository = feedbackRepository;
        }

        [BindProperty]
        public BusinessObject.Reservation Reservation { get; set; }

        [BindProperty]
        public Feedback Feedback { get; set; }

        [BindProperty]
        public string Status { get; set; }

        [BindProperty]
        public string ReservationStatus { get; set; }

        [BindProperty]
        public string Role { get; set; }

        public async Task<IActionResult> OnGet(int? id)
        {
            if(id == null)
            {
                return NotFound();
            }

            try
            {
                Role = User.FindFirstValue(ClaimTypes.Role);
                Reservation = await reservationRepository.GetReservationById((int)id);
                if(Reservation == null)
                {
                    return NotFound();
                } 

                Feedback = feedbackRepository.GetFeedbackByReservationId(Reservation.Id);
                Status = Reservation.Status;
                ReservationStatus = Reservation.Status;
                if(Reservation.ResevrationDate < DateTime.Now)
                {
                    Status = "Invalid";
                }
                if(!AuthorizeForAdminAndChosenDentist(Reservation))
                {
                    return NotFound();
                }
                
                return Page();
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
                
            }
            return LocalRedirect("/Reservation/Index");

        }

        
        public async Task<IActionResult> OnPostAcceptReservation([FromForm] int reservationId)
        {
            try
            {
                BusinessObject.Reservation reservation = await reservationRepository.GetReservationById(reservationId);
                if(reservation == null)
                {
                    return NotFound();
                }

                AuthorizeForAdminAndChosenDentist(reservation);
                reservation.Status = "Accepted";
                reservation.NoteMessage = "";
                await reservationRepository.UpdateReservation(reservation);
                TempData["Message"] = "Update successfully";
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
            }
            return LocalRedirect("/Reservation/Details?id="+reservationId);
        }

        public async Task<IActionResult> OnPostCompleteReservation([FromForm] int reservationId)
        {
            try
            {
                BusinessObject.Reservation reservation = await reservationRepository.GetReservationById(reservationId);
                if (reservation == null)
                {
                    return NotFound();
                }

                AuthorizeForAdminAndChosenDentist(reservation);
                reservation.Status = "Completed";
                await reservationRepository.UpdateReservation(reservation);
                TempData["Message"] = "Update successfully";
            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
            }
            return LocalRedirect("/Reservation/Details?id=" + reservationId);
        }

        public async Task<IActionResult> OnPostRejectReservation([FromForm] int reservationId, string rejectReason)
        {

            try
            {
                BusinessObject.Reservation reservation = await reservationRepository.GetReservationById(reservationId);
                if (reservation == null)
                {
                    return NotFound();
                }
                AuthorizeForAdminAndChosenDentist(reservation);
                reservation.Status = "Rejected";
                if(!string.IsNullOrEmpty(rejectReason.Trim()))
                {
                    reservation.NoteMessage = rejectReason;
                }
                await reservationRepository.UpdateReservation(reservation);
                TempData["Message"] = "Update successfully";
            }
            catch(Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
            }
            return LocalRedirect("/Reservation/Details?id=" + reservationId);
        }

        public async Task<IActionResult> OnPostCancelReservation([FromForm] int reservationId, string rejectReason)
        {
            try
            {
                BusinessObject.Reservation reservation = await reservationRepository.GetReservationById(reservationId);
                if (reservation == null)
                {
                    return NotFound();
                }
                var timeDiff = DateTime.Now - reservation.ResevrationDate;
                if(timeDiff.TotalHours < 1)
                {
                    TempData["ErrorMessage"] = "Only cancel customer's reservation if customer is late for 1 hour.";
                    return LocalRedirect("/Reservation/Details?id=" + reservationId);
                }
                AuthorizeForAdminAndChosenDentist(reservation);
                reservation.Status = "Canceled";
                if (!string.IsNullOrEmpty(rejectReason.Trim()))
                {
                    reservation.NoteMessage = rejectReason;
                }
                await reservationRepository.UpdateReservation(reservation);
                TempData["Message"] = "Cancel successfully";
            }
            catch (Exception)
            {
                TempData["ErrorMessage"] = "There is an error. Please try again later";
            }
            return LocalRedirect("/Reservation/Details?id=" + reservationId);
        }

        public IActionResult OnPostSendFeedback([FromForm] int reservationId, int rate, string comment)
        {
            string email = User.FindFirst(claim => claim.Type == ClaimTypes.Name)?.Value;
            string userId = User.FindFirst(claim => claim.Type == ClaimTypes.NameIdentifier)?.Value;

            try
            {
                Customer customer = customerRepository.GetCustomerByUserId(int.Parse(userId));
                Feedback prevFeedback = feedbackRepository.GetFeedbackByReservationId(reservationId);
                if (prevFeedback == null)
                {
                    Feedback feedback = new Feedback
                    {
                        CustomerId = customer.Id,
                        Star = rate,
                        Comment = comment,
                        ReservationId = reservationId,
                        CreatedDate = DateTime.Now,
                        UpdatedDate = DateTime.Now
                    };
                    feedbackRepository.AddNewFeedback(feedback);
                }
                else
                {
                    prevFeedback.Star = rate;
                    prevFeedback.Comment = comment;
                    prevFeedback.UpdatedDate = DateTime.Now;
                    feedbackRepository.UpdateFeedback(prevFeedback);

                }
                TempData["Message"] = "Send feedback successfully.";

            }
            catch (Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
            }

            return LocalRedirect("/Reservation/Details?id="+ reservationId);
        }

        public async Task<IActionResult> OnPostDeleteFeedback([FromForm] int reservationId)
        {
            string role = User.FindFirst(claim => claim.Type == ClaimTypes.Role)?.Value;
            string userId = User.FindFirst(claim => claim.Type == ClaimTypes.Role)?.Value;
            if(role != "Customer")
            {
                return LocalRedirect("/AccessDenied");
            }
            try
            {
                BusinessObject.Reservation reservation = await reservationRepository.GetReservationById(reservationId);
                Feedback feedback = feedbackRepository.GetFeedbackByReservationId(reservationId);
                if(feedback != null)
                {
                    feedbackRepository.DeleteFeedback(feedback);
                    TempData["Message"] = "Remove feedback successfully";
                }
            }
            catch(Exception ex)
            {
                TempData["ErrorMessage"] = ex.Message;
            }
            return LocalRedirect("/Reservation/Details?id=" + reservationId);
        }
        
        //-------------------------------------------------------------------------------
        private bool AuthorizeForAdminAndChosenDentist(BusinessObject.Reservation reservation)

DentistBooking/DentistBookingWebApp/Pages/Reservation/History.cshtml
@page
@model DentistBookingWebApp.Pages.Reservation.HistoryModel
@{
    ViewData["Title"] = "History";
    int nextPage = ViewBag.CurrentPage + 1;
    int prevPage = ViewBag.CurrentPage - 1;
}

<div class="wrapper">
    <div class="section-title my-3">
        <h2>History</h2>
    </div>
    @if (ViewBag.PageCount > 0)
    {
        <div class="reservation-wrapper row">
            @foreach (var item in Model.Reservations)
            {
                DateTime dateNow = DateTime.Now;

                <div class="reservation-preview d-flex col-12 col-lg-5">
                    <div class="row mb-2">
                        <div class="col-12 col-lg-6">
                            <span class="text-secondary" style="font-weight: 700">Reservation ID: </span>
                            @item.Id
                        </div>
                        <div class="col-12 col-lg-6">
                            <span class="text-secondary" style="font-weight: 700">Service: </span>
                            @item.Service.Name
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-12 col-lg-6">
                            <span class="text-secondary" style="font-weight: 700">Status: </span>
                            @item.Status
                        </div>
                        <div class="col-12 col-lg-6">
                            <span class="text-secondary" style="font-weight: 700">Date: </span>
                            @item.ResevrationDate
                        </div>
                    </div>
                    <div class="row mb-2">
                        <div class="col-12 col-lg-6">
                            <span class="text-secondary" style="font-weight: 700">Price: </span>
                            @item.Price$
                        </div>
                        <div class="col-12 col-lg-6">
                            <span class="text-secondary" style="font-weight: 700">Doctor: </span>
                            @item.Dentist.FullName
                        </div>

                    </div>

                    @* Confirm delete modal *@
                    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Cancel appointment</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    Are you sure to cancel this reservation?
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <form method="post" asp-page-handler="CancelReservation" id="cancelForm">
                                        <input type="hidden" name="reservationId" id="reservationIdInput" />
                                        <button class="btn btn-danger" type="button" onclick="onCancel()">Cancel</button>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="card-button px-3">
                        @if ((DateTime.Now - item.ResevrationDate).TotalMinutes >= 0)
                        {
                            @if (item.Status == "Complete")
                            {
                                <button type="button" class="btn btn-success button-card mx-3" dt data-toggle="modal" data-target="#feedbackModal" data-reservation="@item.Id">Feedback</button>
                            }
                        }
                        else
                        {
                            <button type="button" class="btn btn-danger button-card" dt data-toggle="modal" data-reservation="@item.Id" data-target="#deleteModal">Cancel</button>
                        }
                        <a asp-page="./Details" asp-route-id="@item.Id" class="btn btn-primary button-card mx-3">Detail</a>
                    </div>
                </div>
            }
        </div>
    }
    else
    {
        <h3 class="text-center">
            You have not made any appointment yet.
        </h3>
    }


    @if (ViewBag.PageCount > 1)
    {
        <nav aria-label="..." class="pagination mt-5">
            <ul class="pagination">
                <li class="@(ViewBag.CurrentPage == 1 ? "page-item disabled" : "page-item")">
                    <a class="page-link" href="/Reservation/History?page=@prevPage" tabindex="-1">Previous</a>
                </li>
                @for (int i = 1; i <= ViewBag.PageCount; i++)
                {
                    <li class="@(i == ViewBag.CurrentPage ? "page-item active" : "page-item")">
                        <a class="page-link" href="/Reservation/History?page=@i">@i</a>
                    </li>
                }
                <li class="@(ViewBag.CurrentPage == ViewBag.PageCount ? "page-item disabled" : "page-item")">
                    <a class="page-link" href="/Reservation/History?page=@nextPage">Next</a>
                </li>
            </ul>
        </nav>
    }

</div>

@* Feedback modal *@
<div class="modal fade" id="feedbackModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form method="post" asp-page-handler="SendFeedback" id="feedbackForm">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Feedback our service</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="rating-section col-12">
                        <div>Rating for us (from 1 to 5)</div>
                        <span onmouseover="starmark(this)"
                              onclick="starmark(this)"
                              id="1one"
                              style="font-size: 25px; cursor: pointer"
                              class="fa fa-star checked"></span>
                        <span onmouseover="starmark(this)"
                              onclick="starmark(this)"
                              id="2one"
                              style="font-size: 25px; cursor: pointer"
                              class="fa fa-star"></span>
                        <span onmouseover="starmark(this)"
                              onclick="starmark(this)"
                              id="3one"
                              style="font-size: 25px; cursor: pointer"
                              class="fa fa-star"></span>
                        <span onmouseover="starmark(this)"
                              onclick="starmark(this)"
                              id="4one"
                              style="font-size: 25px; cursor: pointer"
                              class="fa fa-star"></span>
                        <span onmouseover="starmark(this)"
                              onclick="starmark(this)"
                              id="5one"
                              style="font-size: 25px; cursor: pointer"
                              class="fa fa-star"></span><br>
                    </div>
                    <input class="form-control" hidden id="ratePoint" name="rate" />
                    <textarea class="col-12" maxlength="200" name="comment"></textarea>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <input type="hidden" name="reservationId" id="reservationIdInputFeedback" />
                    <button class="btn btn-outline-success" type="button" onclick="onFeedback()">Send feedback</button>
                </div>
            </form>
        </div>
    </div>
</div>


@section Styles {
    <link href="@Url.Content("~/css/reservation/history.css")" rel="stylesheet" type="text/css" />
    <link href="@Url.Content("~/css/feedback/create.css")" rel="stylesheet" type="text/css" />
}

    @section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
        <script src="~/js/feedback/feedback.js"></script>
    }

    <script type="text/javascript">
        window.onload = function() {
            if ('@TempData["Message"]' != "") {
                $.notify("@TempData["Message"]", { color: "#fff", background: "#20D67B" })
            }
            else if ('@TempData["ErrorMessage"]' != "") {
                $.notify("@TempData["ErrorMessage"]", { color: "#fff", background: "#D44950" })
            }
        }
    </script>
    <script>
        function onCancel() {
            $("#cancelForm").submit();
            $(".btn").prop('disabled', true);
        }

        function onFeedback() {
            $("#feedbackForm").submit();
            $(".btn").prop('disabled', true);
        }
    </script>
    <script type="text/javascript">
        $('#deleteModal').on('show.bs.modal', function(event) {
            var button = $(event.relatedTarget);
            var reservationId = button.data('reservation');
            $("#reservationIdInput").val(reservationId);
        })

        $('#feedbackModal').on('show.bs.modal', function(event) {
            var button = $(event.relatedTarget);
            var reservationId = button.data('reservation');
            $("#reservationIdInputFeedback").val(reservationId);
        })
    </script>

    }